/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodaysRatesRouteImport } from './routes/todays-rates'
import { Route as SpecialProgramsRouteImport } from './routes/special-programs'
import { Route as RateNewsRouteImport } from './routes/rate-news'
import { Route as FreeMortgageAdviceRouteImport } from './routes/free-mortgage-advice'
import { Route as ExpatFormRouteImport } from './routes/expat-form'
import { Route as BuyingUsaHomeRouteImport } from './routes/buying-usa-home'
import { Route as BuyAHomeRouteImport } from './routes/buy-a-home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as LandingLowRatesRouteImport } from './routes/landing.low-rates'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedLiveChatRouteImport } from './routes/_authenticated/live-chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TodaysRatesRoute = TodaysRatesRouteImport.update({
  id: '/todays-rates',
  path: '/todays-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialProgramsRoute = SpecialProgramsRouteImport.update({
  id: '/special-programs',
  path: '/special-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RateNewsRoute = RateNewsRouteImport.update({
  id: '/rate-news',
  path: '/rate-news',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeMortgageAdviceRoute = FreeMortgageAdviceRouteImport.update({
  id: '/free-mortgage-advice',
  path: '/free-mortgage-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpatFormRoute = ExpatFormRouteImport.update({
  id: '/expat-form',
  path: '/expat-form',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyingUsaHomeRoute = BuyingUsaHomeRouteImport.update({
  id: '/buying-usa-home',
  path: '/buying-usa-home',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyAHomeRoute = BuyAHomeRouteImport.update({
  id: '/buy-a-home',
  path: '/buy-a-home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLowRatesRoute = LandingLowRatesRouteImport.update({
  id: '/landing/low-rates',
  path: '/landing/low-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveChatRoute = AuthenticatedLiveChatRouteImport.update({
  id: '/live-chat',
  path: '/live-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy-a-home': typeof BuyAHomeRoute
  '/buying-usa-home': typeof BuyingUsaHomeRoute
  '/expat-form': typeof ExpatFormRoute
  '/free-mortgage-advice': typeof FreeMortgageAdviceRoute
  '/rate-news': typeof RateNewsRoute
  '/special-programs': typeof SpecialProgramsRoute
  '/todays-rates': typeof TodaysRatesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/live-chat': typeof AuthenticatedLiveChatRoute
  '/qa': typeof AuthenticatedQaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/landing/low-rates': typeof LandingLowRatesRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy-a-home': typeof BuyAHomeRoute
  '/buying-usa-home': typeof BuyingUsaHomeRoute
  '/expat-form': typeof ExpatFormRoute
  '/free-mortgage-advice': typeof FreeMortgageAdviceRoute
  '/rate-news': typeof RateNewsRoute
  '/special-programs': typeof SpecialProgramsRoute
  '/todays-rates': typeof TodaysRatesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/live-chat': typeof AuthenticatedLiveChatRoute
  '/qa': typeof AuthenticatedQaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/landing/low-rates': typeof LandingLowRatesRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buy-a-home': typeof BuyAHomeRoute
  '/buying-usa-home': typeof BuyingUsaHomeRoute
  '/expat-form': typeof ExpatFormRoute
  '/free-mortgage-advice': typeof FreeMortgageAdviceRoute
  '/rate-news': typeof RateNewsRoute
  '/special-programs': typeof SpecialProgramsRoute
  '/todays-rates': typeof TodaysRatesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/live-chat': typeof AuthenticatedLiveChatRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/landing/low-rates': typeof LandingLowRatesRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buy-a-home'
    | '/buying-usa-home'
    | '/expat-form'
    | '/free-mortgage-advice'
    | '/rate-news'
    | '/special-programs'
    | '/todays-rates'
    | '/admin'
    | '/live-chat'
    | '/qa'
    | '/blog/$slug'
    | '/landing/low-rates'
    | '/programs/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buy-a-home'
    | '/buying-usa-home'
    | '/expat-form'
    | '/free-mortgage-advice'
    | '/rate-news'
    | '/special-programs'
    | '/todays-rates'
    | '/admin'
    | '/live-chat'
    | '/qa'
    | '/blog/$slug'
    | '/landing/low-rates'
    | '/programs/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buy-a-home'
    | '/buying-usa-home'
    | '/expat-form'
    | '/free-mortgage-advice'
    | '/rate-news'
    | '/special-programs'
    | '/todays-rates'
    | '/_authenticated/admin'
    | '/_authenticated/live-chat'
    | '/_authenticated/qa'
    | '/blog/$slug'
    | '/landing/low-rates'
    | '/programs/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuyAHomeRoute: typeof BuyAHomeRoute
  BuyingUsaHomeRoute: typeof BuyingUsaHomeRoute
  ExpatFormRoute: typeof ExpatFormRoute
  FreeMortgageAdviceRoute: typeof FreeMortgageAdviceRoute
  RateNewsRoute: typeof RateNewsRoute
  SpecialProgramsRoute: typeof SpecialProgramsRoute
  TodaysRatesRoute: typeof TodaysRatesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LandingLowRatesRoute: typeof LandingLowRatesRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todays-rates': {
      id: '/todays-rates'
      path: '/todays-rates'
      fullPath: '/todays-rates'
      preLoaderRoute: typeof TodaysRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-programs': {
      id: '/special-programs'
      path: '/special-programs'
      fullPath: '/special-programs'
      preLoaderRoute: typeof SpecialProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-news': {
      id: '/rate-news'
      path: '/rate-news'
      fullPath: '/rate-news'
      preLoaderRoute: typeof RateNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-mortgage-advice': {
      id: '/free-mortgage-advice'
      path: '/free-mortgage-advice'
      fullPath: '/free-mortgage-advice'
      preLoaderRoute: typeof FreeMortgageAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expat-form': {
      id: '/expat-form'
      path: '/expat-form'
      fullPath: '/expat-form'
      preLoaderRoute: typeof ExpatFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buying-usa-home': {
      id: '/buying-usa-home'
      path: '/buying-usa-home'
      fullPath: '/buying-usa-home'
      preLoaderRoute: typeof BuyingUsaHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-a-home': {
      id: '/buy-a-home'
      path: '/buy-a-home'
      fullPath: '/buy-a-home'
      preLoaderRoute: typeof BuyAHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/low-rates': {
      id: '/landing/low-rates'
      path: '/landing/low-rates'
      fullPath: '/landing/low-rates'
      preLoaderRoute: typeof LandingLowRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-chat': {
      id: '/_authenticated/live-chat'
      path: '/live-chat'
      fullPath: '/live-chat'
      preLoaderRoute: typeof AuthenticatedLiveChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLiveChatRoute: typeof AuthenticatedLiveChatRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLiveChatRoute: AuthenticatedLiveChatRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuyAHomeRoute: BuyAHomeRoute,
  BuyingUsaHomeRoute: BuyingUsaHomeRoute,
  ExpatFormRoute: ExpatFormRoute,
  FreeMortgageAdviceRoute: FreeMortgageAdviceRoute,
  RateNewsRoute: RateNewsRoute,
  SpecialProgramsRoute: SpecialProgramsRoute,
  TodaysRatesRoute: TodaysRatesRoute,
  BlogSlugRoute: BlogSlugRoute,
  LandingLowRatesRoute: LandingLowRatesRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
